# Generated by Django 2.1.4 on 2019-02-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20190213_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbank',
            name='direct',
            field=models.BooleanField(default=False),
        ),
    ]
