# Generated by Django 2.1.4 on 2019-02-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbank',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.Business'),
            preserve_default=False,
        ),
    ]
