# Generated by Django 2.1.4 on 2019-03-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_tblbank_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='proofnum',
            field=models.IntegerField(null=True),
        ),
    ]
