# Generated by Django 2.1.4 on 2020-02-26 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_auto_20200217_2103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subsection',
            unique_together={('year', 'institution', 'type', 'code')},
        ),
    ]
