# Generated by Django 2.1.4 on 2020-02-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_auto_20200227_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='session_month',
            field=models.CharField(default='03', max_length=2),
            preserve_default=False,
        ),
    ]
