# Generated by Django 2.1.4 on 2019-04-18 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0023_auto_20190417_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(blank=True, max_length=2, null=True)),
                ('context', models.CharField(max_length=5)),
                ('operation', models.CharField(max_length=14)),
                ('data', models.TextField()),
                ('result_code', models.IntegerField()),
                ('result_msg', models.TextField()),
                ('regdatetime', models.DateTimeField(default=datetime.date.today)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Business')),
            ],
        ),
    ]
