# Generated by Django 2.1.4 on 2019-04-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childcare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='month',
            new_name='gubun',
        ),
        migrations.RemoveField(
            model_name='record',
            name='context',
        ),
    ]
