# Generated by Django 2.1.4 on 2019-04-19 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childcare', '0002_auto_20190418_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='regdatetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='record',
            name='result_code',
            field=models.TextField(),
        ),
    ]
