# Generated by Django 2.1.4 on 2019-01-25 05:20

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renames', models.CharField(max_length=20)),
                ('main', models.BooleanField(default=True)),
                ('account_number', models.CharField(max_length=64)),
                ('account_pw', models.CharField(max_length=20)),
                ('bkdiv', models.CharField(max_length=1)),
                ('Mjumin_1', models.CharField(max_length=6)),
                ('webid', models.CharField(max_length=30)),
                ('webpw', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('reg_number', models.CharField(max_length=12)),
                ('owner_name', models.CharField(max_length=10)),
                ('reg_date', models.DateField(default=datetime.date.today)),
                ('owner_reg_number1', models.CharField(max_length=6)),
                ('owner_reg_number2', models.CharField(max_length=45)),
                ('cellphone', models.CharField(max_length=13)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('fax', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('zip_number', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=45)),
                ('detailed_address', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=27)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('row', models.IntegerField()),
                ('context', models.TextField(blank=True, null=True)),
                ('unit_price', models.TextField(blank=True, null=True)),
                ('cnt', models.TextField(blank=True, null=True)),
                ('months', models.TextField(blank=True, null=True)),
                ('sub_price', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('place_name', models.CharField(max_length=15)),
                ('reg_number', models.CharField(max_length=12)),
                ('owner_name', models.CharField(max_length=10)),
                ('owner_reg_number1', models.CharField(max_length=6)),
                ('owner_reg_number2', models.CharField(max_length=45)),
                ('type1', models.CharField(max_length=10)),
                ('type2', models.CharField(max_length=10)),
                ('cellphone', models.CharField(max_length=13)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('fax', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('zip_number', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=45)),
                ('detailed_address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Business_type',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('context', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level', models.PositiveSmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('name', models.CharField(max_length=10)),
                ('ko_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=30)),
                ('depth', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('has_child', models.BooleanField(default=False)),
                ('target', models.CharField(max_length=10)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Business')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('cellphone', models.CharField(max_length=13)),
                ('place_name', models.CharField(max_length=15)),
                ('reg_number', models.CharField(max_length=12)),
                ('owner_reg_number1', models.CharField(max_length=6)),
                ('owner_reg_number2', models.CharField(max_length=45)),
                ('type1', models.CharField(max_length=10)),
                ('type2', models.CharField(max_length=10)),
                ('fax', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('zip_number', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=45)),
                ('detailed_address', models.CharField(max_length=20)),
                ('is_demo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('context', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.Level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('jdate', models.DateField(default=datetime.date.today)),
                ('reg_number1', models.CharField(max_length=6)),
                ('reg_number2', models.CharField(max_length=45)),
                ('cellphone', models.CharField(max_length=13)),
                ('zip_number', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=45)),
                ('detailed_address', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('account_number', models.CharField(max_length=20)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Agency')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Bank')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('context', models.CharField(max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Business')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2)),
                ('code', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)])),
                ('context', models.CharField(max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Business_type')),
            ],
        ),
        migrations.CreateModel(
            name='TBLBANK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bkid', models.IntegerField()),
                ('Bkdivision', models.IntegerField()),
                ('Mid', models.CharField(max_length=50)),
                ('Bkacctno', models.CharField(max_length=64)),
                ('Bkname', models.CharField(max_length=32)),
                ('Bkdate', models.DateTimeField()),
                ('Bkjukyo', models.CharField(max_length=60)),
                ('sub_Bkjukyo', models.CharField(blank=True, max_length=60, null=True)),
                ('Bkinput', models.BigIntegerField(blank=True, null=True)),
                ('Bkoutput', models.BigIntegerField(blank=True, null=True)),
                ('Bkjango', models.BigIntegerField(blank=True, null=True)),
                ('regdatetime', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Item')),
                ('relative_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_item', to='accounting.Item')),
                ('relative_subsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Subsection')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Subdivision')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bkid', models.IntegerField()),
                ('Bkdivision', models.IntegerField()),
                ('Mid', models.CharField(max_length=50)),
                ('Bkacctno', models.CharField(max_length=64)),
                ('Bkname', models.CharField(max_length=32)),
                ('Bkdate', models.DateTimeField()),
                ('Bkjukyo', models.CharField(max_length=60)),
                ('Bkinput', models.BigIntegerField()),
                ('Bkoutput', models.BigIntegerField()),
                ('Bkjango', models.BigIntegerField()),
                ('regdatetime', models.DateTimeField()),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Business')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Item')),
                ('relative_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relative_item', to='accounting.Item')),
                ('relative_subsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Subsection')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Subdivision')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='paragraph',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Subsection'),
        ),
        migrations.AddField(
            model_name='owner',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.Profile'),
        ),
        migrations.AddField(
            model_name='owner',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Sales'),
        ),
        migrations.AddField(
            model_name='item',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Paragraph'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Owner'),
        ),
        migrations.AddField(
            model_name='business',
            name='type3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Business_type'),
        ),
        migrations.AddField(
            model_name='budget',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Business'),
        ),
        migrations.AddField(
            model_name='budget',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Item'),
        ),
        migrations.AddField(
            model_name='agency',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Bank'),
        ),
        migrations.AddField(
            model_name='agency',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.Profile'),
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Bank'),
        ),
        migrations.AddField(
            model_name='account',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Business'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('Bkid', 'Bkdivision')},
        ),
        migrations.AlterUniqueTogether(
            name='tblbank',
            unique_together={('Bkid', 'Bkdivision')},
        ),
        migrations.AlterUniqueTogether(
            name='subsection',
            unique_together={('institution', 'type', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='subdivision',
            unique_together={('item', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='paragraph',
            unique_together={('subsection', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('business_type', 'url')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('paragraph', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('business', 'year', 'type', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('business', 'account_number')},
        ),
    ]
