# Generated by Django 2.1.4 on 2019-02-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_uploadfile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbank',
            name='Bkacctno',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Bkacctno',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
