# Generated by Django 2.1.4 on 2019-02-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_tblbank_direct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbank',
            name='Bkname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Bkname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
