# Generated by Django 2.1.4 on 2019-03-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_transaction_proofnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='proofnum',
            field=models.IntegerField(),
        ),
    ]
