# Generated by Django 2.1.4 on 2019-03-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_auto_20190311_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Mjumin_1',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
