# Generated by Django 2.1.4 on 2019-04-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_transaction_direct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='direct',
        ),
    ]
