# Generated by Django 2.1.4 on 2019-04-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_remove_transaction_direct'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='s_auth_key',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
