# Generated by Django 2.1.4 on 2019-04-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_business_s_auth_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='s_auth_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
