# Generated by Django 2.1.4 on 2019-04-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_auto_20190412_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='s_auth_key',
            new_name='c_auth_key',
        ),
    ]
