# Generated by Django 2.0.13 on 2020-02-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_auto_20190710_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.CharField(default='2019', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paragraph',
            name='year',
            field=models.CharField(default='2019', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsection',
            name='year',
            field=models.CharField(default='2019', max_length=4),
            preserve_default=False,
        ),
    ]
